# vim: set softtabstop=2 tabstop=2 shiftwidth=2:
name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.6

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Setup PATH environment variable
      run: |
        echo "::add-path::~/.local/bin"
        echo "::add-path::./bin"

    - name: Install pre-commit
      run: pip install wheel pre-commit

    - name: Install
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.6

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Generate code automatically
      run: go generate -v ./...

    - name: Build
      run: go build -v .

    - name: Check commits via pre-commit hooks
      run: pre-commit run --all-files
